// IDDN FR.001.250001.005.S.P.2019.000.00000
// ILIAD is subject to copyright laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2022

#pragma once

#include "CoreMinimal.h"
#include "OdysseyPerformanceMode.h"
#include "OdysseyMediaProvider.h"
#include "OdysseyLayer.generated.h"

class UOdysseyLayerStack;

UENUM(BlueprintType)
enum  class  EGetLayerChildrenMethod : uint8
{
    DepthFirst,
    BreadthFirst
};

UCLASS(Abstract, BlueprintType, config=EditorPerProjectUserSettings, PerObjectConfig)
class ODYSSEYLAYERSTACK_API UOdysseyLayer
	: public UObject
{
    GENERATED_BODY()

    friend UOdysseyLayerStack;

public:
    /**
     * @brief Delegate called when something changed the result of RenderImage()
     * 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnNameChanged, UOdysseyLayer*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     * 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnIsActivatedChanged, UOdysseyLayer*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     * 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnIsLockedChanged, UOdysseyLayer*)

    /* DisplayChildrenChanged
     * - concerned Child 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnDisplayChildrenChanged, UOdysseyLayer*);

    /* DisplayOptionsChanged
     * - concerned Child 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnDisplayOptionsChanged, UOdysseyLayer*);

    /* ParentChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnParentChanged, UOdysseyLayer*);

    /* ChildrenChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnChildrenChanged, UOdysseyLayer*);


public:
    static FOnNameChanged& OnNameChanged();
    static FOnIsActivatedChanged& OnIsActivatedChanged();
    static FOnIsLockedChanged& OnIsLockedChanged();
    static FOnDisplayChildrenChanged& OnDisplayChildrenChanged();
    static FOnDisplayOptionsChanged& OnDisplayOptionsChanged();
    static FOnParentChanged& OnParentChanged();
    static FOnChildrenChanged& OnChildrenChanged();
    static FSimpleMulticastDelegate& OnMediaChanged();
    
public:
    // Events

    /**
	 * @brief Called when the node has been created by the given LayerStack
	 *
	 */
    UFUNCTION(BlueprintNativeEvent, Category = "LayerStack")
    void OnCreated();
    virtual void OnCreated_Implementation();

public:
    // API

    /**
     * @brief Returns the Layer parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    UOdysseyLayer* GetParent() const;

    /**
     * @brief Returns the Layer parents from direct parent to root parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    TArray<UOdysseyLayer*> GetParents() const;

    /**
     * @brief Returns the Layer direct children
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    const TArray<UOdysseyLayer*>& GetChildren() const;

    /**
     * @brief Returns the Layer children recursively
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    TArray<UOdysseyLayer*> GetChildrenRecursively(EGetLayerChildrenMethod Method = EGetLayerChildrenMethod::DepthFirst) const;

    /**
     * @brief Returns the Layer index in its parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    int GetIndexInParent() const;

    /**
     * @brief Returns wether the given layer is a child of the given ParentLayer
     *
     * @param Layer
     * @param ParentLayer
     * @return bool
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack")
    bool IsChildOf(UOdysseyLayer* Layer) const;

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack" )
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    UFUNCTION(BlueprintPure, Category = "LayerStack" )
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> LayerTypes) const;

    /**
     * @brief Merges the given layers into this layer
     * Only works with Layer class being a child of classes returned by GetMergeLayerTypes()
     */
    UFUNCTION(BlueprintCallable, Category = "LayerStack")
    virtual void Merge(const TArray<UOdysseyLayer*>& Layers);

public:
    // Getters
    /**
	 * @brief Returns the topmost parent of this node
	 *
	 */
    UFUNCTION(BlueprintPure, Category="LayerStack")
    UOdysseyLayerStack* GetLayerStack() const;

    UFUNCTION(BlueprintPure, Category="LayerStack")
    bool GetIsActivatedRecursively() const;

    UFUNCTION(BlueprintPure, Category="LayerStack")
    bool GetIsLockedRecursively() const;

    virtual FOdysseyMediaProvider GetMediaProvider(uint32 iFrameIndex) const;

protected:
    //Property changed methods
    virtual void NameChanged();
    virtual void IsActivatedChanged();
    virtual void IsLockedChanged();
    virtual void DisplayChildrenChanged();
    virtual void DisplayOptionsChanged();
    virtual void ParentChanged();
    virtual void ChildrenChanged();

    virtual void PropertyChanged(const FName& iPropertyName);

public:
    // UObject overrides
    virtual void PostEditChangeProperty( FPropertyChangedEvent& PropertyChangedEvent) override;
    virtual void PostTransacted(const FTransactionObjectEvent& iTransactionEvent) override;

public:
    //Default properties
    UPROPERTY(EditDefaultsOnly, Category="Layer")
    FText LayerTypeName = FText::FromString(TEXT("Unnamed Layer Type"));

    UPROPERTY(EditDefaultsOnly, Category="Layer")
    FText DefaultName = FText::FromString(TEXT("Layer"));

    UPROPERTY(EditDefaultsOnly, Category="Layer")
	FText Description = FText::FromString(TEXT(""));

    //UPROPERTY(EditDefaultsOnly, Category="Layer")
    FSlateIcon Icon;

    //UPROPERTY(EditDefaultsOnly, Category="Layer")
    FSlateIcon IconExpanded;
    
    //Defaults Properties
    UPROPERTY(EditDefaultsOnly, Category="Layer")
	bool CanHaveChildren = false;

protected:
    //Instance properties (protected)

public:
    //Instance properties
    UPROPERTY(EditInstanceOnly, BlueprintReadWrite, Category="LayerStack|Layer")
    FText Name;

    UPROPERTY(EditInstanceOnly, BlueprintReadWrite, Category="LayerStack|Layer")
    bool IsActivated = true;

    UPROPERTY(EditInstanceOnly, BlueprintReadWrite, Category="LayerStack|Layer")
    bool IsLocked = false;

    UPROPERTY(BlueprintReadWrite, Category="LayerStack|Layer")
    bool DisplayChildren = true;

    UPROPERTY(BlueprintReadWrite, Category="LayerStack|Layer")
    bool DisplayOptions = true;

    UPROPERTY()
    UOdysseyLayer* Parent;

    UPROPERTY()
    TArray<UOdysseyLayer*> Children;
};