// IDDN.FR.001.250001.005.S.P.2019.000.00000
// ILIAD is subject to copyright laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2022

#pragma once

#include "CoreMinimal.h"
#include "Image/OdysseyBlendingMode.h"
#include "OdysseyPerformanceMode.h"
#include "OdysseyMediaProvider.h"
#include "OdysseyImageRenderingAbility.h"
#include "Textures/SlateIcon.h"
#include "Layout/Margin.h"

#include "OdysseyLayer.generated.h"

class UOdysseyLayerStack;

UENUM(BlueprintType)
enum  class  EGetLayerChildrenMethod : uint8
{
    DepthFirst,
    BreadthFirst
};

UCLASS(Abstract, HideDropdown, BlueprintType, config=EditorPerProjectUserSettings, PerObjectConfig)
class ODYSSEYLAYERSTACK_API UOdysseyLayer
    : public UObject
    , public FOdysseyImageRenderingAbility
{
    GENERATED_BODY()

    friend UOdysseyLayerStack;

public:
    /**
     * @brief Delegate called when something changed the result of RenderImage()
     *
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnNameChanged, UOdysseyLayer*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     *
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnIsActivatedChanged, UOdysseyLayer*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     *
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnIsLockedChanged, UOdysseyLayer*)

    /* DisplayChildrenChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnDisplayChildrenChanged, UOdysseyLayer*);

    /* DisplayOptionsChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnDisplayOptionsChanged, UOdysseyLayer*);

    /* ParentChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnParentChanged, UOdysseyLayer*);

    /* ChildrenChanged
     * - concerned Child
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnChildrenChanged, UOdysseyLayer*);

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     *
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnBlendModeChanged, UOdysseyLayer*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     *
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnOpacityChanged, UOdysseyLayer*)


public:
    static FOnNameChanged& OnNameChanged();
    static FOnIsActivatedChanged& OnIsActivatedChanged();
    static FOnIsLockedChanged& OnIsLockedChanged();
    static FOnDisplayChildrenChanged& OnDisplayChildrenChanged();
    static FOnDisplayOptionsChanged& OnDisplayOptionsChanged();
    static FOnParentChanged& OnParentChanged();
    static FOnChildrenChanged& OnChildrenChanged();
    static FSimpleMulticastDelegate& OnMediaChanged();
    static FOnBlendModeChanged& OnBlendModeChanged();
    static FOnOpacityChanged& OnOpacityChanged();

public:
    // API

    /**
     * @brief Returns the Layer parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    UOdysseyLayer* GetParent() const;

    /**
     * @brief Returns the Layer parents from direct parent to root parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    TArray<UOdysseyLayer*> GetParents() const;

    /**
     * @brief Returns the Layer direct children
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    const TArray<UOdysseyLayer*>& GetChildren() const;

    /**
     * @brief Returns the Layer children recursively
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    TArray<UOdysseyLayer*> GetChildrenRecursively(EGetLayerChildrenMethod Method = EGetLayerChildrenMethod::DepthFirst) const;

    /**
     * @brief Returns the Layer index in its parent
     *
     * @param Layer
     * @return int
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    int GetIndexInParent() const;

    /**
     * @brief Returns wether the given layer is a child of the given ParentLayer
     *
     * @param Layer
     * @param ParentLayer
     * @return bool
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    bool IsChildOf(UOdysseyLayer* Layer) const;

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer" )
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer" )
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> LayerTypes) const;

    /**
     * @brief Merges the given layers into this layer
     * Only works with Layer class being a child of classes returned by GetMergeLayerTypes()
     */
    UFUNCTION(BlueprintCallable, Category="Odyssey|Layer")
    virtual void Merge(const TArray<UOdysseyLayer*>& Layers);

public:
    // Getters
    /**
     * @brief Returns the topmost parent of this node
     *
     */
    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    virtual UOdysseyLayerStack* GetLayerStack() const;

    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    bool IsActivatedRecursively() const;

    UFUNCTION(BlueprintPure, Category="Odyssey|Layer")
    bool IsLockedRecursively() const;

public:
    virtual TArray<FGuid> GetImageRenderingComposition(IOdysseyImageRenderer::eRenderType iRenderType, int iFrame) const override;
    virtual TArray<::ULIS::FRectI> GetImageRenderingRects() const override;
    virtual TSharedPtr<IOdysseyImageRenderer> BuildImageRenderer(IOdysseyImageRenderer::eRenderType iRenderType, int iFrame, FImageRendererFilter iFilter = FImageRendererFilter()) const override;
    virtual FOdysseyMediaProvider GetMediaProvider(uint32 iFrameIndex) const;

    public:
    #ifdef WITH_EDITOR
        virtual TArray<FName> GetRows() const;
        virtual int GetRowHeight(FName iSubRowName) const;
        virtual bool IsRowVisible(FName iSubRowName) const;
        virtual FMargin GetRowPadding(FName iSubRowName) const;
    #endif

protected:
    //Property changed methods
    virtual void NameChanged();
    virtual void IsActivatedChanged();
    virtual void IsLockedChanged();
    virtual void DisplayChildrenChanged();
    virtual void DisplayOptionsChanged();
    virtual void ParentChanged();
    virtual void ChildrenChanged();
    virtual void OpacityChanged(bool iIsInteractive);
    virtual void BlendModeChanged();

    virtual void PropertyChanged(const FName& iPropertyName, const FName& iMemberPropertyName, bool iIsInteractive);
    virtual void PostPropertyChanged(const FName& iPropertyName, bool iIsInteractive);

public:
    // UObject overrides
    virtual void PostEditChangeProperty( FPropertyChangedEvent& PropertyChangedEvent) override;
    virtual void PostTransacted(const FTransactionObjectEvent& iTransactionEvent) override;

public:
    //Default properties
    UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    FText LayerTypeName = FText::FromString(TEXT("Unnamed Layer Type"));

    UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    FText DefaultName = FText::FromString(TEXT("Layer"));

    UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    FText Description = FText::FromString(TEXT(""));

    //UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    FSlateIcon Icon;

    //UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    FSlateIcon IconExpanded;

    //Defaults Properties
    UPROPERTY(EditDefaultsOnly, Category="Odyssey|Layer")
    bool CanHaveChildren = false;

    UPROPERTY()
    UOdysseyLayer* Parent;

    UPROPERTY()
    TArray<UOdysseyLayer*> Children;

private:
    //Instance properties
    UFUNCTION(BlueprintSetter)
    void NameBlueprintSetter(FText Value);

    UFUNCTION(BlueprintSetter)
    void IsActivatedBlueprintSetter(bool Value);

    UFUNCTION(BlueprintSetter)
    void IsLockedBlueprintSetter(bool Value);

    UFUNCTION(BlueprintSetter)
    void DisplayChildrenBlueprintSetter(bool Value);

    UFUNCTION(BlueprintSetter)
    void DisplayOptionsBlueprintSetter(bool Value);

    UFUNCTION(BlueprintSetter)
    void BlendModeBlueprintSetter(EOdysseyBlendingMode Value);

    UFUNCTION(BlueprintSetter)
    void OpacityBlueprintSetter(float Value);

public:
    //Instance properties
    UPROPERTY(BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=NameBlueprintSetter)
    FText Name;

    UPROPERTY(BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=IsActivatedBlueprintSetter)
    bool IsActivated = true;

    UPROPERTY(BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=IsLockedBlueprintSetter)
    bool IsLocked = false;

    UPROPERTY(BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=DisplayChildrenBlueprintSetter)
    bool DisplayChildren = true;

    UPROPERTY(BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=DisplayOptionsBlueprintSetter)
    bool DisplayOptions = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=BlendModeBlueprintSetter)
    EOdysseyBlendingMode BlendMode = EOdysseyBlendingMode::kNormal;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Odyssey|Layer", BlueprintSetter=OpacityBlueprintSetter)
    float Opacity = 1.0f;
};
