#include "/Engine/Private/common.ush"

// BlendMode Seperarable
#define ODYSSEY_BLENDINGMODE_Normal 0
#define ODYSSEY_BLENDINGMODE_Top 1
#define ODYSSEY_BLENDINGMODE_Back 2
#define ODYSSEY_BLENDINGMODE_Behind 3
#define ODYSSEY_BLENDINGMODE_Dissolve 4
#define ODYSSEY_BLENDINGMODE_BayerDither8x8 5
#define ODYSSEY_BLENDINGMODE_Darken 6
#define ODYSSEY_BLENDINGMODE_Multiply 7
#define ODYSSEY_BLENDINGMODE_ColorBurn 8
#define ODYSSEY_BLENDINGMODE_LinearBurn 9
#define ODYSSEY_BLENDINGMODE_DarkerColor 10
#define ODYSSEY_BLENDINGMODE_Lighten 11
#define ODYSSEY_BLENDINGMODE_Screen 12
#define ODYSSEY_BLENDINGMODE_ColorDodge 13
#define ODYSSEY_BLENDINGMODE_LinearDodge 14
#define ODYSSEY_BLENDINGMODE_LighterColor 15
#define ODYSSEY_BLENDINGMODE_Overlay 16
#define ODYSSEY_BLENDINGMODE_SoftLight 17
#define ODYSSEY_BLENDINGMODE_HardLight 18
#define ODYSSEY_BLENDINGMODE_VividLight 19
#define ODYSSEY_BLENDINGMODE_LinearLight 20
#define ODYSSEY_BLENDINGMODE_PinLight 21
#define ODYSSEY_BLENDINGMODE_HardMix 22
#define ODYSSEY_BLENDINGMODE_Phoenix 23
#define ODYSSEY_BLENDINGMODE_Reflect 24
#define ODYSSEY_BLENDINGMODE_Glow 25
#define ODYSSEY_BLENDINGMODE_Difference 26
#define ODYSSEY_BLENDINGMODE_Exclusion 27
#define ODYSSEY_BLENDINGMODE_Add 28
#define ODYSSEY_BLENDINGMODE_Substract 29
#define ODYSSEY_BLENDINGMODE_Divide 30
#define ODYSSEY_BLENDINGMODE_Average 31
#define ODYSSEY_BLENDINGMODE_Negation 32
#define ODYSSEY_BLENDINGMODE_Hue 33
#define ODYSSEY_BLENDINGMODE_Saturation 34
#define ODYSSEY_BLENDINGMODE_Color 35
#define ODYSSEY_BLENDINGMODE_Luminosity 36
#define ODYSSEY_BLENDINGMODE_PartialDerivative 37
#define ODYSSEY_BLENDINGMODE_WhiteOut 38
#define ODYSSEY_BLENDINGMODE_AngleCorrected 39

// AlphaMode
#define ODYSSEY_ALPHAMODE_Normal 0
#define ODYSSEY_ALPHAMODE_Erase 1
#define ODYSSEY_ALPHAMODE_Top 2
#define ODYSSEY_ALPHAMODE_Back 3
#define ODYSSEY_ALPHAMODE_Sub 4
#define ODYSSEY_ALPHAMODE_Add 5
#define ODYSSEY_ALPHAMODE_Mul 6
#define ODYSSEY_ALPHAMODE_Min 7
#define ODYSSEY_ALPHAMODE_Max 8

bool IsBlendSeparable(uint iBlendingMode)
{
    switch (iBlendingMode)
    {
        case ODYSSEY_BLENDINGMODE_Normal:
        case ODYSSEY_BLENDINGMODE_Top:
        case ODYSSEY_BLENDINGMODE_Back:
        case ODYSSEY_BLENDINGMODE_Behind:
        case ODYSSEY_BLENDINGMODE_Darken:
        case ODYSSEY_BLENDINGMODE_Multiply:
        case ODYSSEY_BLENDINGMODE_ColorBurn:
        case ODYSSEY_BLENDINGMODE_LinearBurn:
        case ODYSSEY_BLENDINGMODE_Lighten:
        case ODYSSEY_BLENDINGMODE_Screen:
        case ODYSSEY_BLENDINGMODE_ColorDodge:
        case ODYSSEY_BLENDINGMODE_LinearDodge:
        case ODYSSEY_BLENDINGMODE_Overlay:
        case ODYSSEY_BLENDINGMODE_SoftLight:
        case ODYSSEY_BLENDINGMODE_HardLight:
        case ODYSSEY_BLENDINGMODE_VividLight:
        case ODYSSEY_BLENDINGMODE_LinearLight:
        case ODYSSEY_BLENDINGMODE_PinLight:
        case ODYSSEY_BLENDINGMODE_HardMix:
        case ODYSSEY_BLENDINGMODE_Phoenix:
        case ODYSSEY_BLENDINGMODE_Reflect:
        case ODYSSEY_BLENDINGMODE_Glow:
        case ODYSSEY_BLENDINGMODE_Difference:
        case ODYSSEY_BLENDINGMODE_Exclusion:
        case ODYSSEY_BLENDINGMODE_Add:
        case ODYSSEY_BLENDINGMODE_Substract:
        case ODYSSEY_BLENDINGMODE_Divide:
        case ODYSSEY_BLENDINGMODE_Average:
        case ODYSSEY_BLENDINGMODE_Negation:
            return true;

        case ODYSSEY_BLENDINGMODE_Dissolve:       // Misc Blend
        case ODYSSEY_BLENDINGMODE_BayerDither8x8: // Misc Blend
        case ODYSSEY_BLENDINGMODE_DarkerColor:
        case ODYSSEY_BLENDINGMODE_LighterColor:
        case ODYSSEY_BLENDINGMODE_Hue:
        case ODYSSEY_BLENDINGMODE_Saturation:
        case ODYSSEY_BLENDINGMODE_Color:
        case ODYSSEY_BLENDINGMODE_Luminosity:
        case ODYSSEY_BLENDINGMODE_PartialDerivative:
        case ODYSSEY_BLENDINGMODE_WhiteOut:
        case ODYSSEY_BLENDINGMODE_AngleCorrected:
            return false;
    }

    return false;
}

// Simple solid color pixel shader
float Lum(float3 iC)
{
    return iC.x * 0.3 + iC.y * 0.59 + iC.z * 0.11;
}

float3 ClipColor(float3 iC)
{
    float3 c = iC;
    float l = Lum(iC);
    float n = min3(iC.x, iC.y, iC.z);
    float x = max3(iC.x, iC.y, iC.z);
    if (n < 0.f)
    {
        c.x = l + (((c.x - l) * l) / (l - n));
        c.y = l + (((c.y - l) * l) / (l - n));
        c.z = l + (((c.z - l) * l) / (l - n));
    }
    else if (x > 1.f)
    {
        c.x = l + (((c.x - l) * (1.f - l)) / (x - l));
        c.y = l + (((c.y - l) * (1.f - l)) / (x - l));
        c.z = l + (((c.z - l) * (1.f - l)) / (x - l));
    }

    return c;
}

float3 SetLum(float3 iC, float iL)
{
    float d = iL - Lum(iC);
    iC.x = iC.x + d;
    iC.y = iC.y + d;
    iC.z = iC.z + d;

    return ClipColor(iC);
}

float Sat(float3 iC)
{
    return max3(iC.x, iC.y, iC.z) - min3(iC.x, iC.y, iC.z);
}

float3 SetSatComponent(float3 iC, int iIndex, float iValue)
{
    if (iIndex == 0)
    {
        iC.x = iValue;
    }
    else if (iIndex == 1)
    {
        iC.y = iValue;
    }
    else
    {
        iC.z = iValue;
    }

    return iC;
}

float3 SetSatMid(float3 iC, float iS)
{
}

float3 SetSatMax(float3 iC, float iS)
{
}

float3 SetSat(float3 iC, float iS)
{
    int minIndex = (iC.x < iC.y) ? ((iC.x < iC.z) ? 0 : 2) : ((iC.y < iC.z) ? 1 : 2);
    int maxIndex = (iC.x > iC.y) ? ((iC.x > iC.z) ? 0 : 2) : ((iC.y > iC.z) ? 1 : 2);
    int midIndex = 3 - minIndex - maxIndex;
    if (iC[maxIndex] > iC[minIndex])
    {
        float midValue = (((iC[midIndex] - iC[minIndex]) * iS) / (iC[maxIndex] - iC[minIndex]));
        float maxValue = iS;
        iC = SetSatComponent(iC, midIndex, midValue);
        iC = SetSatComponent(iC, maxIndex, maxValue);
    }
    else
    {
        iC = SetSatComponent(iC, midIndex, 0.f);
        iC = SetSatComponent(iC, maxIndex, 0.f);
    }
    iC = SetSatComponent(iC, minIndex, 0.f);
    return iC;
}

float BlendNormal(float iCb, float iCs)
{
    return iCs;
}

float BlendTop(float iCb, float iCs)
{
    return iCs;
}

float BlendBack(float iCb, float iCs)
{
    return iCb;
}

float BlendBehind(float iCb, float iCs)
{
    return iCb;
}

float BlendDarken(float iCb, float iCs)
{
    return min(iCb, iCs);
}

float BlendMultiply(float iCb, float iCs)
{
    return iCb * iCs;
}

float BlendColorBurn(float iCb, float iCs)
{
    return iCs > 0.f ? (1.f - min(1.f, (1.f - iCb) / iCs)) : 0.f;
}

float BlendLighten(float iCb, float iCs)
{
    return max(iCb, iCs);
}

float BlendAverage(float iCb, float iCs)
{
    return (iCs + iCb) / 2.f;
}

float BlendNegation(float iCb, float iCs)
{
    return 1.f - abs(1.f - iCs - iCb);
}

float BlendScreen(float iCb, float iCs)
{
    return iCb + iCs - (iCb * iCs);
}

float BlendColorDodge(float iCb, float iCs)
{
    return iCs == 1.0f ? 1.f : min(1.f, iCb / (1.f - iCs));
}

float BlendAdd(float iCb, float iCs)
{
    return min(1.f, iCs + iCb);
}

float BlendLinearDodge(float iCb, float iCs)
{
    return min(1.f, iCs + iCb);
}

float BlendSoftLight(float iCb, float iCs)
{
    if (iCs <= 0.5f)
    {
        return iCb - (1.f - 2.f * iCs) * iCb * (1 - iCb);
    }

    float d = iCb <= 0.25f ? ((16.f * iCb - 12.f) * iCb + 4) * iCb : sqrt(iCb);
    return iCb + (2.f * iCs - 1.f) * (d * iCb);
}

float BlendLinearBurn(float iCb, float iCs)
{
    return max(0.f, iCs + iCb - 1.f);
}

float BlendHardLight(float iCb, float iCs)
{
    return iCs <= 0.5f ? BlendMultiply(iCb, 2.f * iCs) : BlendScreen(iCb, 2 * iCs - 1.f);
}

float BlendOverlay(float iCb, float iCs)
{
    return BlendHardLight(iCs, iCb);
}

float BlendVividLight(float iCb, float iCs)
{
    return iCs <= 0.5f ? BlendColorBurn(iCb, 2 * iCs) : BlendColorDodge(iCb, 2 * (iCs - 0.5f));
}

float BlendLinearLight(float iCb, float iCs)
{
    return clamp(iCb + 2.f * iCs - 1.f, 0.f, 1.f);
}

float BlendPinLight(float iCb, float iCs)
{
    return iCs > 0.5f ? max(iCb, 2.f * iCs - 1.f) : min(iCb, 2.f * iCs);
}

float BlendHardMix(float iCb, float iCs)
{
    return iCs + iCb < 0.999f ? 0 : iCs + iCb > 1.001f ? 1.f : iCb > iCs            ? 1.f : 0.f;
}

float BlendDifference(float iCb, float iCs)
{
    return abs(iCb - iCs);
}

float BlendExclusion(float iCb, float iCs)
{
    return iCb + iCs - 2.f * iCb * iCs;
}

float BlendSubstract(float iCb, float iCs)
{
    return max(0.f, iCb - iCs);
}

float BlendDivide(float iCb, float iCs)
{
    return iCs == 0.f && iCb == 0.f ? 0.f : iCs == 0.f && iCb != 0.f ? 1.f : clamp(iCb / iCs, 0.f, 1.f);
}

float BlendPhoenix(float iCb, float iCs)
{
    return 1.f - max(iCs, iCb) + min(iCs, iCb);
}

float BlendReflect(float iCb, float iCs)
{
    return iCb == 1.f ? 1.f : min(1.f, iCs * iCs / (1.f - iCb));
}

float BlendGlow(float iCb, float iCs)
{
    return BlendReflect(iCs, iCb);
}

//--------------------------------------------------------------------------------------
//-------------------------------------------------------------------------- DarkerColor
float3 BlendDarkerColor(float3 iCs, float3 iCb) {
    return Lum(iCb) < Lum(iCs) ? iCb : iCs;
}
//--------------------------------------------------------------------------------------
//------------------------------------------------------------------------- LighterColor
float3 BlendLighterColor(float3 iCs, float3 iCb) {
    return Lum(iCb) > Lum(iCs) ? iCb : iCs;
}

float3 BlendHue(float3 iCb, float3 iCs)
{
    return SetLum(SetSat(iCs, Sat(iCb)), Lum(iCb));
}

float3 BlendSaturation(float3 iCb, float3 iCs)
{
    return SetLum(SetSat(iCb, Sat(iCs)), Lum(iCb));
}

float3 BlendColor(float3 iCb, float3 iCs)
{
    return SetLum(iCs, Lum(iCb));
}

float3 BlendLuminosity(float3 iCb, float3 iCs)
{
    return SetLum(iCb, Lum(iCs));
}

float Distance(float3 iValue)
{
    return sqrt(iValue.x * iValue.x + iValue.y * iValue.y + iValue.z * iValue.z);
}

float3 Normalize(float3 iValue)
{
    float distance = Distance(iValue);
    if (distance == 0)
        return float3(0, 0, 0);

    return float3(
        iValue.x / distance,
        iValue.y / distance,
        iValue.z / distance
    );
}

//--------------------------------------------------------------------------------------
//------------------------------------------------------------------- Partial Derivative
float3 BlendPartialDerivative(float3 iCs, float3 iCb) {
    float3 cs = iCs * 2.f - 1.f;
    float3 cb = iCb * 2.f - 1.f;

    float3 res = float3(cs.x * cb.z + cb.x * cs.z, cs.y * cb.z + cb.y * cs.z, cs.z * cb.z);
    res = Normalize(res) * 0.5f + 0.5f;
    return res;
}
//--------------------------------------------------------------------------------------
//----------------------------------------------------------------------------- Whiteout
float3 BlendWhiteOut(float3 iCs, float3 iCb) {
    float3 cs = iCs * 2.f - 1.f;
    float3 cb = iCb * 2.f - 1.f;
    float3 res = float3(cs.x + cb.x, cs.y + cb.y, cs.z * cb.z);
    res = Normalize(res) * 0.5f + 0.5f;
    return res;
}
//--------------------------------------------------------------------------------------
//----------------------------------------------------------------------- AngleCorrected
float3 BlendAngleCorrected(float3 iCs, float3 iCb) {
    float3 cs = iCs * 2.f - 1.f;
    float3 cb = iCb * 2.f - 1.f;
    float3 res = float3(cs.x + cb.x, cs.y + cb.y, cs.z);
    res = Normalize(res) * 0.5f + 0.5f;
    return res;
}

float BlendComponent(float iCb, float iCs, uint iBlendingMode)
{
    switch (iBlendingMode)
    {
        case ODYSSEY_BLENDINGMODE_Normal:
        {
            return BlendNormal(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Top:
        {
            return BlendTop(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Back:
        {
            return BlendBack(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Behind:
        {
            return BlendBehind(iCb, iCs);
        }
        break;

        /* TODO: See ULIS
        case ODYSSEY_BLENDINGMODE_Dissolve:
        {
            return BlendDissolve(iCb, iCs);
        }
        break; */

        /* TODO: See ULIS
        case ODYSSEY_BLENDINGMODE_BayerDither8x8:
        {
            return BlendBayerDither8x8(iCb, iCs);
        }
        break; */

        case ODYSSEY_BLENDINGMODE_Darken:
        {
            return BlendDarken(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Multiply:
        {
            return BlendMultiply(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_ColorBurn:
        {
            return BlendColorBurn(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_LinearBurn:
        {
            return BlendLinearBurn(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Lighten:
        {
            return BlendLighten(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Screen:
        {
            return BlendScreen(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_ColorDodge:
        {
            return BlendColorDodge(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_LinearDodge:
        {
            return BlendLinearDodge(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Overlay:
        {
            return BlendOverlay(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_SoftLight:
        {
            return BlendSoftLight(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_HardLight:
        {
            return BlendHardLight(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_VividLight:
        {
            return BlendVividLight(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_LinearLight:
        {
            return BlendLinearLight(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_PinLight:
        {
            return BlendPinLight(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_HardMix:
        {
            return BlendHardMix(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Phoenix:
        {
            return BlendPhoenix(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Reflect:
        {
            return BlendReflect(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Glow:
        {
            return BlendGlow(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Difference:
        {
            return BlendDifference(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Exclusion:
        {
            return BlendExclusion(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Add:
        {
            return BlendAdd(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Substract:
        {
            return BlendSubstract(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Divide:
        {
            return BlendDivide(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Average:
        {
            return BlendAverage(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Negation:
        {
            return BlendNegation(iCb, iCs);
        }
        break;
    }

    return 0.f;
}

float AlphaNormal(float iCb, float iCs)
{
    return iCb + iCs - (iCb * iCs);
}

float AlphaErase(float iCs, float iCb) {
    return (1.f - iCs) * iCb;
}

float AlphaBack(float iCs, float iCb) {
    return iCb;
}

float AlphaTop(float iCs, float iCb) {
    return iCs;
}

float AlphaSub(float iCs, float iCb) {
    return iCb > iCs ? iCb - iCs : 0;
}

float AlphaAdd(float iCs, float iCb) {
    return (1.f - iCb) > iCs ? iCb + iCs : 1.f;
}

float AlphaMul(float iCs, float iCb) {
    return iCb * iCs;
}

float AlphaMin(float iCs, float iCb) {
    return min(iCs, iCb);
}

float AlphaMax(float iCs, float iCb) {
    return max(iCs, iCb);
}

float AlphaBlend(float iCb, float iCs, uint iAlphaBlend)
{
    switch (iAlphaBlend)
    {
        case ODYSSEY_ALPHAMODE_Normal:
        {
            return AlphaNormal(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Erase:
        {
            return AlphaErase(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Top:
        {
            return AlphaTop(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Back:
        {
            return AlphaBack(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Sub:
        {
            return AlphaSub(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Add:
        {
            return AlphaAdd(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Mul:
        {
            return AlphaMul(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Min:
        {
            return AlphaMin(iCs, iCb);
        }
        break;

        case ODYSSEY_ALPHAMODE_Max:
        {
            return AlphaMax(iCs, iCb);
        }
        break;
    }

    return 0.f;
}

float4 BlendSeparable(float4 iCb, float4 iCs, float iOpacity, uint iBlendMode, uint iAlphaMode)
{
    float4 outColor = float4(0.f, 0.f, 0.f, 0.f);

    float csR = iCs.x;
    float cbR = iCb.x;
    float csG = iCs.y;
    float cbG = iCb.y;
    float csB = iCs.z;
    float cbB = iCb.z;
    float csA = iCs.w * iOpacity;
    float cbA = iCb.w;
    if (csA == 0.f)
        return iCb;

    float comp = AlphaNormal(cbA, csA);
    outColor.x = (1.0f - (csA / comp)) * cbR + (csA / comp) * ((1.0f - cbA) * csR + cbA * BlendComponent(cbR, csR, iBlendMode));
    outColor.y = (1.0f - (csA / comp)) * cbG + (csA / comp) * ((1.0f - cbA) * csG + cbA * BlendComponent(cbG, csG, iBlendMode));
    outColor.z = (1.0f - (csA / comp)) * cbB + (csA / comp) * ((1.0f - cbA) * csB + cbA * BlendComponent(cbB, csB, iBlendMode));

    outColor.w = AlphaBlend(cbA, csA, iAlphaMode);

    return outColor;
}

float3 BlendNonSeparableComponents(float3 iCb, float3 iCs, uint iBlendMode)
{
    switch (iBlendMode)
    {
        case ODYSSEY_BLENDINGMODE_DarkerColor:
        {
            return BlendDarkerColor(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_LighterColor:
        {
            return BlendLighterColor(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Hue:
        {
            return BlendHue(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Saturation:
        {
            return BlendSaturation(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Color:
        {
            return BlendColor(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_Luminosity:
        {
            return BlendLuminosity(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_PartialDerivative:
        {
            return BlendPartialDerivative(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_WhiteOut:
        {
            return BlendWhiteOut(iCb, iCs);
        }
        break;

        case ODYSSEY_BLENDINGMODE_AngleCorrected:
        {
            return BlendAngleCorrected(iCb, iCs);
        }
        break;
    }
    return float3(0, 0, 0);
}

float4 BlendNonSeparable(float4 iCb, float4 iCs, float iOpacity, uint iBlendMode, uint iAlphaMode)
{
    float4 outColor = float4(0.f, 0.f, 0.f, 0.f);

    float csR = iCs.x;
    float cbR = iCb.x;
    float csG = iCs.y;
    float cbG = iCb.y;
    float csB = iCs.z;
    float cbB = iCb.z;
    float csA = iCs.w * iOpacity;
    float cbA = iCb.w;
    if (csA == 0.f)
        return iCb;

    float comp = AlphaNormal(cbA, csA);

    float3 cb3 = float3(iCb.x, iCb.y, iCb.z);
    float3 cs3 = float3(iCs.x, iCs.y, iCs.z);
    float3 components = BlendNonSeparableComponents(cb3, cs3, iBlendMode);

    outColor.x = (1.0f - (csA / comp)) * cbR + (csA / comp) * ((1.0f - cbA) * csR + cbA * components.x);
    outColor.y = (1.0f - (csA / comp)) * cbG + (csA / comp) * ((1.0f - cbA) * csG + cbA * components.y);
    outColor.z = (1.0f - (csA / comp)) * cbB + (csA / comp) * ((1.0f - cbA) * csB + cbA * components.z);

    outColor.w = AlphaBlend(cbA, csA, iAlphaMode);

    return outColor;
}

float4 Blend(float4 iCb, float4 iCs, float iOpacity, uint iBlendMode, uint iAlphaMode)
{
    // TODO: ODYSSEY_BLENDINGMODE_Dissolve Misc blend
    // TODO: ODYSSEY_BLENDINGMODE_BayerDither8x8 Misc blend

    if (IsBlendSeparable(iBlendMode))
        return BlendSeparable(iCb, iCs, iOpacity, iBlendMode, iAlphaMode);

    return BlendNonSeparable(iCb, iCs, iOpacity, iBlendMode, iAlphaMode);
}
