#include "/Engine/Private/common.ush"

// Simple solid color pixel shader

Texture2D DestinationTexture;
Texture2D SourceTexture;
float2 SourcePosition;
float2 SourceSize;
SamplerState SourceTextureSampler;
float2 DestinationPosition;
float2 DestinationSize;
SamplerState DestinationTextureSampler;
float Opacity;

float Lum(float3 iC)
{
    return iC.x * 0.3 + iC.y * 0.59 + iC.z * 0.11;
}

float3 ClipColor(float3 iC)
{
    float3 c = iC;
    float l = Lum(iC);
    float n = min3(iC.x, iC.y, iC.z);
    float x = max3(iC.x, iC.y, iC.z);
    if (n < 0.f)
    {
        c.x = l + (((c.x - l) * l) / (l - n));
        c.y = l + (((c.y - l) * l) / (l - n));
        c.z = l + (((c.z - l) * l) / (l - n));
    }
    else if (x > 1.f)
    {
        c.x = l + (((c.x - l) * (1.f - l)) / (x - l));
        c.y = l + (((c.y - l) * (1.f - l)) / (x - l));
        c.z = l + (((c.z - l) * (1.f - l)) / (x - l));
    }

    return c;
}

float3 SetLum(float3 iC, float iL)
{
    float d = iL - Lum(iC);
    iC.x = iC.x + d;
    iC.y = iC.y + d;
    iC.z = iC.z + d;

    return ClipColor(iC);
}

float Sat(float3 iC)
{
    return max3(iC.x, iC.y, iC.z) - min3(iC.x, iC.y, iC.z);
}

float3 SetSat(float3 iC, float iS)
{
    int minIndex = (iC.x < iC.y) ? ((iC.x < iC.z) ? 0 : 2) : ((iC.y < iC.z) ? 1 : 2);
    int maxIndex = (iC.x > iC.y) ? ((iC.x > iC.z) ? 0 : 2) : ((iC.y > iC.z) ? 1 : 2);
    int midIndex = 3 - minIndex - maxIndex;
    if (iC[maxIndex] > iC[minIndex])
    {
        iC[midIndex] = (((iC[midIndex] - iC[minIndex]) * iS) / (iC[maxIndex] - iC[minIndex]));
        iC[maxIndex] = iS;
    }
    else
    {
        iC[midIndex] = 0.f;
        iC[maxIndex] = 0.f;
    }
    iC[minIndex] = 0.f;
    return iC;
}

void GetSourcePixel(
    float2 TextureCoordinate,
    out float4 oFG
)
{
    oFG = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
}

float Union(float iCb, float iCs)
{
    return iCb + iCs - (iCb * iCs);
}

float4 Blend(float4 iCb, float4 iCs, float3 iBlendComponents)
{
    float4 outColor = float4(0.f, 0.f, 0.f, 0.f);

    float csR = iCs.x;
    float cbR = iCb.x;
    float csG = iCs.y;
    float cbG = iCb.y;
    float csB = iCs.z;
    float cbB = iCb.z;
    float csA = iCs.w * Opacity;
    float cbA = iCb.w;
    if (csA == 0.f)
        return iCb;

    float alphaResult = Union(cbA, csA);
    outColor.x = (1.0f - (csA / alphaResult)) * cbR + (csA / alphaResult) * ((1.0f - cbA) * csR + cbA * iBlendComponents.x);
    outColor.y = (1.0f - (csA / alphaResult)) * cbG + (csA / alphaResult) * ((1.0f - cbA) * csG + cbA * iBlendComponents.y);
    outColor.z = (1.0f - (csA / alphaResult)) * cbB + (csA / alphaResult) * ((1.0f - cbA) * csB + cbA * iBlendComponents.z);
    outColor.w = alphaResult;

    return outColor;
}

float BlendNormal(float iCb, float iCs)
{
    return iCs;
}

float BlendTop(float iCb, float iCs)
{
    return iCs;
}

float BlendBack(float iCb, float iCs)
{
    return iCb;
}

float BlendBehind(float iCb, float iCs)
{
    return iCb;
}

float BlendDarken(float iCb, float iCs)
{
    return min(iCb, iCs);
}

float BlendMultiply(float iCb, float iCs)
{
    return iCb * iCs;
}

float BlendColorBurn(float iCb, float iCs)
{
    return iCs > 0.f ? (1.f - min(1.f, (1.f - iCb) / iCs)) : 0.f;
}

float BlendLighten(float iCb, float iCs)
{
    return max(iCb, iCs);
}

float BlendAverage(float iCb, float iCs)
{
    return (iCs + iCb) / 2.f;
}

float BlendNegation(float iCb, float iCs)
{
    return 1.f - abs(1.f - iCs - iCb);
}

float BlendScreen(float iCb, float iCs)
{
    return iCb + iCs - (iCb * iCs);
}

float BlendColorDodge(float iCb, float iCs)
{
    return iCs == 1.0f ? 1.f : min(1.f, iCb / (1.f - iCs));
}

float BlendAdd(float iCb, float iCs)
{
    return min(1.f, iCs + iCb);
}

float BlendLinearDodge(float iCb, float iCs)
{
    return min(1.f, iCs + iCb);
}

float BlendSoftLight(float iCb, float iCs)
{
    if (iCs <= 0.5f)
    {
        return iCb - (1.f - 2.f * iCs) * iCb * (1 - iCb);
    }

    float d = iCb <= 0.25f ? ((16.f * iCb - 12.f) * iCb + 4) * iCb : sqrt(iCb);
    return iCb + (2.f * iCs - 1.f) * (d * iCb);
}

float BlendLinearBurn(float iCb, float iCs)
{
    return max(0.f, iCs + iCb - 1.f);
}

float BlendHardLight(float iCb, float iCs)
{
    return iCs <= 0.5f ? BlendMultiply(iCb, 2.f * iCs) : BlendScreen(iCb, 2 * iCs - 1.f);
}

float BlendOverlay(float iCb, float iCs)
{
    return BlendHardLight(iCs, iCb);
}

float BlendVividLight(float iCb, float iCs)
{
    return iCs <= 0.5f ? BlendColorBurn(iCb, 2 * iCs) : BlendColorDodge(iCb, 2 * (iCs - 0.5f));
}

float BlendLinearLight(float iCb, float iCs)
{
    return clamp(iCb + 2.f * iCs - 1.f, 0.f, 1.f);
}

float BlendPinLight(float iCb, float iCs)
{
    return iCs > 0.5f ? max(iCb, 2.f * iCs - 1.f) : min(iCb, 2.f * iCs);
}

float BlendHardMix(float iCb, float iCs)
{
    return iCs + iCb < 0.999f ? 0 : iCs + iCb > 1.001f ? 1.f : iCb > iCs ? 1.f : 0.f;
}

float BlendDifference(float iCb, float iCs)
{
    return abs(iCb - iCs);
}

float BlendExclusion(float iCb, float iCs)
{
    return iCb + iCs - 2.f * iCb * iCs;
}

float BlendSubstract(float iCb, float iCs)
{
    return max(0.f, iCb - iCs);
}

float BlendDivide(float iCb, float iCs)
{
    return iCs == 0.f && iCb == 0.f ? 0.f : iCs == 0.f && iCb != 0.f ? 1.f : clamp(iCb / iCs, 0.f, 1.f);
}

float BlendPhoenix(float iCb, float iCs)
{
    return 1.f - max(iCs, iCb) + min(iCs, iCb);
}

float BlendReflect(float iCb, float iCs)
{
    return iCb == 1.f ? 1.f : min(1.f, iCs * iCs / (1.f - iCb));
}

float BlendGlow(float iCb, float iCs)
{
    return BlendReflect(iCs, iCb);
}

float3 BlendHue(float3 iCb, float3 iCs)
{
    return SetLum(SetSat(iCs, Sat(iCb)), Lum(iCb));
}

float3 BlendSaturation(float3 iCb, float3 iCs)
{
    return SetLum(SetSat(iCb, Sat(iCs)), Lum(iCb));
}

float3 BlendColor(float3 iCb, float3 iCs)
{
    return SetLum(iCs, Lum(iCb));
}

float3 BlendLuminosity(float3 iCb, float3 iCs)
{
    return SetLum(iCb, Lum(iCs));
}

void BlendNormalPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    //ReplicateChannel(BaseColor, TextureComponentReplicate, TextureComponentReplicateAlpha);

    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendNormal(cb.x, cs.x),
        BlendNormal(cb.y, cs.y),
        BlendNormal(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendTopPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendTop(cb.x, cs.x),
        BlendTop(cb.y, cs.y),
        BlendTop(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendBackPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendBack(cb.x, cs.x),
        BlendBack(cb.y, cs.y),
        BlendBack(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendBehindPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendBehind(cb.x, cs.x),
        BlendBehind(cb.y, cs.y),
        BlendBehind(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendDarkenPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendDarken(cb.x, cs.x),
        BlendDarken(cb.y, cs.y),
        BlendDarken(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendMultiplyPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendMultiply(cb.x, cs.x),
        BlendMultiply(cb.y, cs.y),
        BlendMultiply(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendColorBurnPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendColorBurn(cb.x, cs.x),
        BlendColorBurn(cb.y, cs.y),
        BlendColorBurn(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendLightenPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendLighten(cb.x, cs.x),
        BlendLighten(cb.y, cs.y),
        BlendLighten(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendAveragePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendAverage(cb.x, cs.x),
        BlendAverage(cb.y, cs.y),
        BlendAverage(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendNegationPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendNegation(cb.x, cs.x),
        BlendNegation(cb.y, cs.y),
        BlendNegation(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendScreenPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendScreen(cb.x, cs.x),
        BlendScreen(cb.y, cs.y),
        BlendScreen(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendColorDodgePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendColorDodge(cb.x, cs.x),
        BlendColorDodge(cb.y, cs.y),
        BlendColorDodge(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendAddPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendAdd(cb.x, cs.x),
        BlendAdd(cb.y, cs.y),
        BlendAdd(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendLinearDodgePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendLinearDodge(cb.x, cs.x),
        BlendLinearDodge(cb.y, cs.y),
        BlendLinearDodge(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendSoftLightPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendSoftLight(cb.x, cs.x),
        BlendSoftLight(cb.y, cs.y),
        BlendSoftLight(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendLinearBurnPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendLinearBurn(cb.x, cs.x),
        BlendLinearBurn(cb.y, cs.y),
        BlendLinearBurn(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendHardLightPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendHardLight(cb.x, cs.x),
        BlendHardLight(cb.y, cs.y),
        BlendHardLight(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendOverlayPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendOverlay(cb.x, cs.x),
        BlendOverlay(cb.y, cs.y),
        BlendOverlay(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendVividLightPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendVividLight(cb.x, cs.x),
        BlendVividLight(cb.y, cs.y),
        BlendVividLight(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendLinearLightPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendLinearLight(cb.x, cs.x),
        BlendLinearLight(cb.y, cs.y),
        BlendLinearLight(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendPinLightPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendPinLight(cb.x, cs.x),
        BlendPinLight(cb.y, cs.y),
        BlendPinLight(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendHardMixPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendHardMix(cb.x, cs.x),
        BlendHardMix(cb.y, cs.y),
        BlendHardMix(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendDifferencePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendDifference(cb.x, cs.x),
        BlendDifference(cb.y, cs.y),
        BlendDifference(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendExclusionPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendExclusion(cb.x, cs.x),
        BlendExclusion(cb.y, cs.y),
        BlendExclusion(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendSubstractPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendSubstract(cb.x, cs.x),
        BlendSubstract(cb.y, cs.y),
        BlendSubstract(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendDividePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendDivide(cb.x, cs.x),
        BlendDivide(cb.y, cs.y),
        BlendDivide(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendPhoenixPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendPhoenix(cb.x, cs.x),
        BlendPhoenix(cb.y, cs.y),
        BlendPhoenix(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendReflectPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendReflect(cb.x, cs.x),
        BlendReflect(cb.y, cs.y),
        BlendReflect(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendGlowPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 blendComponents = float3(
        BlendGlow(cb.x, cs.x),
        BlendGlow(cb.y, cs.y),
        BlendGlow(cb.z, cs.z)
    );
    OutColor = Blend(cb, cs, blendComponents);
}

void BlendHuePS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 cb3 = float3(cb.x, cb.y, cb.z);
    float3 cs3 = float3(cs.x, cs.y, cs.z);
    OutColor = Blend(cb, cs, BlendHue(cb3, cs3));
}

void BlendSaturationPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 cb3 = float3(cb.x, cb.y, cb.z);
    float3 cs3 = float3(cs.x, cs.y, cs.z);
    OutColor = Blend(cb, cs, BlendSaturation(cb3, cs3));
}

void BlendColorPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 cb3 = float3(cb.x, cb.y, cb.z);
    float3 cs3 = float3(cs.x, cs.y, cs.z);
    OutColor = Blend(cb, cs, BlendColor(cb3, cs3));
}

void BlendLuminosityPS(
	in float2 TextureCoordinate : TEXCOORD0,
	in float4 Color : TEXCOORD1,
	in float4 HitProxyId : TEXCOORD2,
	out float4 OutColor : SV_Target0
)
{
    float4 cb = DestinationTexture.Sample(DestinationTextureSampler, TextureCoordinate);
    float4 cs = SourceTexture.Sample(SourceTextureSampler, TextureCoordinate);
    float3 cb3 = float3(cb.x, cb.y, cb.z);
    float3 cs3 = float3(cs.x, cs.y, cs.z);
    OutColor = Blend(cb, cs, BlendLuminosity(cb3, cs3));
}

/* void MainVS(
    float4 InLargeWorldCoordinatesHigh: ATTRIBUTE0,
    float4 InLargeWorldCoordinatesLow: ATTRIBUTE1,
    float2 InTextureCoordinate: ATTRIBUTE2,
    float4 InColor: ATTRIBUTE3,
    //float4 InHitProxyIdColor: ATTRIBUTE4,
    out float4 OutVertexCoord: SV_POSITION,
    out float2 OutTexCoord : TEXCOORD0
)
{
    OutVertexCoord = float4(InLargeWorldCoordinatesHigh.x * 2.f - 1.0f, (1.0f - InLargeWorldCoordinatesHigh.y) * 2.f - 1.0f, InLargeWorldCoordinatesHigh.z, InLargeWorldCoordinatesHigh.w);
    OutTexCoord = InTextureCoordinate;
} */
