#include "/Engine/Public/Platform.ush"

/**
    RLE Format for fast GPU decompression

    The Format is composed of 3 buffers :
    - TileDescriptors
    - RLEData
    - SequenceData

    TileDescriptors is an array of FTileDesctiptor.
    Each FTileDesctiptor decribes where to find the tile data in the RLEData buffer.
    If FTileDesctiptor does contains a negative position, then the tile is considered empty.

    RLEData is a buffer containing RLE-like data.
    RLE Data is composed of multiple couples of data.
    Each couple contains a position (position of the first pixel affected) and a Value.
    The position of the next used to know the position of the mlast pixel affected.
    Also if the next position is positive, the value represents a pixel to repeat.
    If the next position is negative, the value represents a pointer to the SequenceData buffer.

    SequenceData contains all the data that is not a repetition.

    TileDescriptors : [FTileDesctiptor][FTileDesctiptor][FTileDesctiptor][FTileDesctiptor]
                            |
                            |
                 -----------
                |
                v
    RLEData : [+Position][Value][-Position][Pointer][+Position][Value][-Position][Pointer]
                                    |                                       |
                                    |                                       |
                                    |                                       |
                    ----------------                       -----------------
                   |                                      |
                   v                                      v
    SequenceData : [                Data                 ][        Data                ]
*/

struct FTileDescriptor
{
    int position; //position in RLETilePositions
    uint count; //number of positions in RLETilePositions corresponding to this tile
};

uint TileWidth; //Width of 1 tile in pixels
uint TileHeight; //Height of 1 tile in pixels
uint TextureHeight; //Width of the final Texture
uint TextureWidth; //Height of the final Texture
uint BytesPerComponent; //Size of a Pixel in 32-bits
StructuredBuffer<FTileDescriptor> TileDescriptors; //Contains informations about tiles (which tile contains data and where to find taht data in the RLEBuffer
StructuredBuffer<int> RLEPositions; //Contains position of each valid RLE Data in RLEData
StructuredBuffer<uint> RLEData; //Contains position of each valid RLE Data in RLEData
StructuredBuffer<uint> SequenceData; //Contains each valid tile data compressed in RLE
RWTexture2D<float4> OutputTexture; //The output Texture where the uncompressed data will be stored

uint2 GetNumTiles()
{
    return uint2 (
        max(1, ((TextureWidth - 1) / TileWidth) + 1),
        max(1, ((TextureHeight - 1) / TileHeight) + 1)
    );
}

uint2 GetTileSize(uint2 iTile)
{
    uint2 endTilePos = uint2((iTile.x + 1) * TileWidth, (iTile.y + 1) * TileHeight);
    return uint2(
        TileWidth - max(0, int(endTilePos.x - TextureWidth)),
        TileHeight - max(0, int(endTilePos.y - TextureHeight))
    );
}

float4 GetRLEDataValueAt(uint OffsetInBuffer)
{
    if (BytesPerComponent == 1)
    {
        return float4(
            (RLEData[OffsetInBuffer * BytesPerComponent] & 0x000000FF) / 255.0,
            (RLEData[OffsetInBuffer * BytesPerComponent] & 0x0000FF00) / 255.0,
            (RLEData[OffsetInBuffer * BytesPerComponent] & 0x00FF0000) / 255.0,
            (RLEData[OffsetInBuffer * BytesPerComponent] & 0xFF000000) / 255.0
        );
    }
    else if (BytesPerComponent == 2)
    {
        return float4(
            f16tof32(RLEData[OffsetInBuffer * BytesPerComponent] & 0x0000FFFF),
            f16tof32((RLEData[OffsetInBuffer * BytesPerComponent] & 0xFFFF0000) >> 16),
            f16tof32(RLEData[OffsetInBuffer * BytesPerComponent + 1] & 0x0000FFFF),
            f16tof32((RLEData[OffsetInBuffer * BytesPerComponent + 1] & 0x0000FFFF) >> 16)
        );
    }
    else if (BytesPerComponent == 4)
    {
        return float4(
            asfloat(RLEData[OffsetInBuffer * BytesPerComponent]),
            asfloat(RLEData[OffsetInBuffer * BytesPerComponent + 1]),
            asfloat(RLEData[OffsetInBuffer * BytesPerComponent + 2]),
            asfloat(RLEData[OffsetInBuffer * BytesPerComponent + 3])
        );
    }

    return float4(0.f, 0.f, 0.f, 0.f);
}

float4 GetSequenceDataValueAt(uint OffsetInBuffer)
{
    if (BytesPerComponent == 1)
    {
        return float4(
            (SequenceData[OffsetInBuffer * BytesPerComponent] & 0x000000FF) / 255.0,
            (SequenceData[OffsetInBuffer * BytesPerComponent] & 0x0000FF00) / 255.0,
            (SequenceData[OffsetInBuffer * BytesPerComponent] & 0x00FF0000) / 255.0,
            (SequenceData[OffsetInBuffer * BytesPerComponent] & 0xFF000000) / 255.0
        );
    }
    else if (BytesPerComponent == 2)
    {
        return float4(
            f16tof32(SequenceData[OffsetInBuffer * BytesPerComponent] & 0x0000FFFF),
            f16tof32((SequenceData[OffsetInBuffer * BytesPerComponent] & 0xFFFF0000) >> 16),
            f16tof32(SequenceData[OffsetInBuffer * BytesPerComponent + 1] & 0x0000FFFF),
            f16tof32((SequenceData[OffsetInBuffer * BytesPerComponent + 1] & 0x0000FFFF) >> 16)
        );
    }
    else if (BytesPerComponent == 4)
    {
        return float4(
            asfloat(SequenceData[OffsetInBuffer * BytesPerComponent]),
            asfloat(SequenceData[OffsetInBuffer * BytesPerComponent + 1]),
            asfloat(SequenceData[OffsetInBuffer * BytesPerComponent + 2]),
            asfloat(SequenceData[OffsetInBuffer * BytesPerComponent + 3])
        );
    }

    return float4(0.f, 0.f, 0.f, 0.f);
}

bool GetTileDescriptor(in uint2 iTile, out FTileDescriptor oTileDescriptor)
{
    uint2 numTiles = GetNumTiles();

    FTileDescriptor descriptor = TileDescriptors[iTile.y * numTiles.x + iTile.x];
    if (descriptor.position < 0) //if position is negative tile is considered empty
        return false;

    oTileDescriptor = descriptor;
    return true;
}

bool GetPixelOffsetInRLEData(in uint2 iTile, in uint iPixelPosition, out uint oRLEStartPosition, out uint oRLEOffset)
{
    FTileDescriptor tileDescriptor;
    if (!GetTileDescriptor(iTile, tileDescriptor))
        return false;

    //recherche dicotomique
    uint low = abs(tileDescriptor.position);
    uint high = abs(tileDescriptor.position) + tileDescriptor.count - 1;
    while (low <= high)
    {
        uint mid = low + (high - low) / 2;
        uint pos = abs(RLEPositions[mid]);
        uint posNext = abs(RLEPositions[mid + 1]);

        if (iPixelPosition >= pos && iPixelPosition < posNext)
        {
            oRLEStartPosition = mid;
            oRLEOffset = 0;
            return true;
        }

        // If x is smaller, ignore right half
        if (iPixelPosition < posNext)
        {
            high = mid - 1;
        }
        // If x greater, ignore left half
        else
        {
            low = mid + 1;
        }
    }

    //Should not happen
    return false;
}

void ReadRLE(uint iRLEStartPosition, uint iRLEOffset, uint iTilePosition, uint Count, uint2 tile)
{
    uint2 tileSize = GetTileSize(tile);

    uint RLEPosition = iRLEStartPosition;
    uint RLEOffset = iRLEOffset;
    uint count = Count;
    uint currentTilePos = iTilePosition;
    while (count > 0)
    {
        int firstPosition = RLEPositions[RLEPosition];
        int lastPosition = RLEPositions[RLEPosition + 1];
        uint numPixels = min(abs(lastPosition) - abs(firstPosition) - RLEOffset, count);
        if (lastPosition > 0) //Repetition
        {
            float4 pixelValue = GetRLEDataValueAt(RLEPosition);
            for (uint i = 0; i < numPixels; i++)
            {
                uint2 texturePos = uint2(
                    tile.x * TileWidth + ((currentTilePos + i) % tileSize.x),
                    tile.y * TileHeight + ((currentTilePos + i) / tileSize.y)
                );
                OutputTexture[texturePos] = pixelValue;
            }
            currentTilePos += numPixels;
        }
        else //Sequence
        {
            uint pointer = RLEData[RLEPosition * BytesPerComponent] + RLEOffset;
            for (uint i = 0; i < numPixels; i++)
            {
                float4 pixelValue = GetSequenceDataValueAt(pointer + i);
                uint2 texturePos = uint2(
                    tile.x * TileWidth + ((currentTilePos + i) % tileSize.x),
                    tile.y * TileHeight + ((currentTilePos + i) / tileSize.y)
                );
                OutputTexture[texturePos] = pixelValue;
            }
            currentTilePos += numPixels;
        }
        RLEPosition = RLEPosition + 1;
        RLEOffset = 0;
        count = count - numPixels;
    }
}

#define NUM_THREADS_X 8
#define NUM_THREADS_Y 8
#define NUM_TOTAL_THREADS (NUM_THREADS_X * NUM_THREADS_Y)

//32 * 32 * 1 = 1024 threads which is the maximum authorized amount of threads in ComputeShaders V5
//(see: https://learn.microsoft.com/fr-fr/windows/win32/direct3dhlsl/sm5-attributes-numthreads)
[numthreads(NUM_THREADS_X, NUM_THREADS_Y, 1)]
void Main(
	uint3 DispatchThreadId : SV_DispatchThreadID,
    uint3 GroupId : SV_GroupID,
    uint GroupIndex : SV_GroupIndex,
	uint3 GroupThreadId : SV_GroupThreadID )
{
    uint2 tile = GroupId.xy;
    uint2 tileSize = GetTileSize(tile);

/*
    Example of repartition of pixels by thread

    GroupIndex       =>   0    1    2    3    | numPixelsPerTile | minThreadPixelCount | maxThreadPixelCount |
    threadPixelCount => [ 1 ][ 0 ][ 0 ][ 0 ]  | 1                | 0                   | 1
    threadPixelCount => [ 1 ][ 1 ][ 0 ][ 0 ]  | 2                | 0                   | 1
    threadPixelCount => [ 1 ][ 1 ][ 1 ][ 0 ]  | 3                | 0                   | 1
    threadPixelCount => [ 1 ][ 1 ][ 1 ][ 1 ]  | 4                | 0                   | 1
    threadPixelCount => [ 2 ][ 1 ][ 1 ][ 1 ]  | 5                | 1                   | 2
    threadPixelCount => [ 2 ][ 2 ][ 1 ][ 1 ]  | 6                | 1                   | 2
    threadPixelCount => [ 2 ][ 2 ][ 2 ][ 1 ]  | 7                | 1                   | 2
    threadPixelCount => [ 2 ][ 2 ][ 2 ][ 2 ]  | 8                | 1                   | 2
    threadPixelCount => [ 3 ][ 2 ][ 2 ][ 2 ]  | 9                | 2                   | 3
    threadPixelCount => [ 3 ][ 3 ][ 2 ][ 2 ]  | 10               | 2                   | 3
    threadPixelCount => [ 3 ][ 3 ][ 3 ][ 2 ]  | 11               | 2                   | 3
    threadPixelCount => [ 3 ][ 3 ][ 3 ][ 3 ]  | 12               | 2                   | 3
*/

    uint numPixelsPerTile = tileSize.x * tileSize.y;
    if (numPixelsPerTile <= 0) //Makes no sense to have negative or null amount of pixels to process
        return;

    uint minThreadPixelCount = (numPixelsPerTile - 1) / NUM_TOTAL_THREADS;
    uint maxThreadPixelCount = minThreadPixelCount + 1;
    uint threadPixelCount = maxThreadPixelCount;
    if ((GroupIndex * maxThreadPixelCount) + (NUM_TOTAL_THREADS - GroupIndex) * minThreadPixelCount >= numPixelsPerTile)
        threadPixelCount = minThreadPixelCount;

    if (threadPixelCount <= 0) //No pixel to process for this thread
        return;

    uint numThreadAtMaxPixelCount = numPixelsPerTile - (NUM_TOTAL_THREADS * minThreadPixelCount);
    uint firstPixel = min(GroupIndex, numThreadAtMaxPixelCount) * maxThreadPixelCount + max(0, int(GroupIndex - numThreadAtMaxPixelCount)) * minThreadPixelCount;
    uint lastPixel = firstPixel + threadPixelCount - 1;

    uint RLEStartPosition = 1;
    uint RLEOffset = 1;

    //If GetPixelOffsetInRLEData returns false, the tile is considered empty
    if (!GetPixelOffsetInRLEData(tile, firstPixel, RLEStartPosition, RLEOffset))
    {
        for (uint i = firstPixel; i <= lastPixel; i++)
        {
            uint2 texturePos = uint2(
                tile.x * TileWidth + (i % tileSize.x),
                tile.y * TileHeight + (i / tileSize.x)
            );
            OutputTexture[texturePos] = float4(1.f, 0.f, 0.f, 1.f);
        }
        return;
    }

    /* for (uint y = 0; y < TileHeight; y++)
    {
        for (uint x = 0; x < TileWidth; x++)
        {
            uint2 texturePos = uint2(
                min( TextureWidth - 1, tile.x * TileWidth + x),
                min( TextureHeight - 1, tile.y * TileHeight + y)
            );
            OutputTexture[texturePos] = float4(1.f, 0.f, 0.f, 1.f);
        }
    }*/

    /*for (uint y = 0; y < TileHeight/NUM_THREADS_Y; y++)
    {
        for (uint x = 0; x < TileWidth/NUM_THREADS_X; x++)
        {
            OutputTexture[DispatchThreadId.xy * uint2(TileWidth/NUM_THREADS_X, TileHeight/NUM_THREADS_Y) + uint2(x, y)] = float4(
                float(RLEStartPosition),
                float(RLEOffset),
                0.f,
                1.f
            );
        }
    }*/

    ReadRLE(RLEStartPosition, RLEOffset, firstPixel, threadPixelCount, tile);
}