#include "/OdysseyShaders/Private/OdysseyBlendCommon.ush"
#include "/Engine/Public/Platform.ush"

// Simple solid color pixel shader

Texture2D DestinationTexture;
Texture2D SourceTexture;
SamplerState SourceTextureSampler;
SamplerState DestinationTextureSampler;
float Opacity;
uint BlendMode;
uint AlphaMode;

void MainPS(
    in float2 InTextureCoordinate: TEXCOORD0,
    in float4 InColor: TEXCOORD1,
    in float4 InHitProxyId: TEXCOORD2,
    in float4 InVertexPosition: SV_POSITION,
    out float4 OutColor: SV_Target0
)
{
    float2 destinationSize = float2(0.f, 0.f);
    float destinationLODCount = 0;
    DestinationTexture.GetDimensions(0, destinationSize.x, destinationSize.y, destinationLODCount);
    float2 dstCoordinate = float2(InVertexPosition.x / destinationSize.x, InVertexPosition.y / destinationSize.y);

    float4 cb = float4(0.f, 0.f, 0.f, 0.f);
    if (dstCoordinate.x >= 0.0f && dstCoordinate.y >= 0.0f && dstCoordinate.x <= 1.0f && dstCoordinate.y <= 1.0f)
    {
        cb = DestinationTexture.Sample(DestinationTextureSampler, dstCoordinate);
    }

    float4 cs = float4(0.f, 0.f, 0.f, 0.f);
    if (InTextureCoordinate.x >= 0.0f && InTextureCoordinate.y >= 0.0f && InTextureCoordinate.x <= 1.0f && InTextureCoordinate.y <= 1.0f)
    {
        cs = SourceTexture.Sample(SourceTextureSampler, InTextureCoordinate);
    }

    OutColor = Blend(cb, cs, Opacity, BlendMode, AlphaMode, uint2(int(floor(InVertexPosition.x)), int(floor(InVertexPosition.y))));
}
