#include "/Engine/Public/Platform.ush"

//------------------------------------------------------------------
// HSV functions : Copied from "/Engine/Private/Substrate/ColorSpace.ush"
//------------------------------------------------------------------

float3 HUE_2_LinearRGB(in float H)
{
	float R = abs(H * 6 - 3) - 1;
	float G = 2 - abs(H * 6 - 2);
	float B = 2 - abs(H * 6 - 4);
	return saturate(float3(R, G, B));
}

float3 HSV_2_LinearRGB(in float3 HSV)
{
	float3 RGB = HUE_2_LinearRGB(HSV.x);
	return ((RGB - 1) * HSV.y + 1) * HSV.z;
}

float3 RGB_2_HCV(in float3 RGB)
{
	// Based on work by Sam Hocevar and Emil Persson
	float4 P = (RGB.g < RGB.b)	? float4(RGB.bg, -1.0f, 2.0f / 3.0f): float4(RGB.gb, 0.0f, -1.0f / 3.0f);
	float4 Q = (RGB.r < P.x)	? float4(P.xyw, RGB.r)				: float4(RGB.r, P.yzx);
	float Chroma = Q.x - min(Q.w, Q.y);
	float Hue = abs((Q.w - Q.y) / (6.0f * Chroma + 1e-10f) + Q.z);
	return float3(Hue, Chroma, Q.x);
}

float3 LinearRGB_2_HSV(in float3 RGB)
{
	float3 HCV = RGB_2_HCV(RGB);
	float s = HCV.y / (HCV.z + 1e-10f);
	return float3(HCV.x, s, HCV.z);
}

//---------------------------------------------------------

Texture2D SourceTexture;
SamplerState SourceTextureSampler;

Texture2D AdjustCurveTexture;
SamplerState AdjustCurveTextureSampler;

float ColorSaturation;
float ColorValue;

float Grayscale(float3 color)
{
	return 0.299 * color.r + 0.587 * color.g + 0.114 * color.b;
}

void MainPS(
    float4 SvPosition : SV_POSITION,
	out float4 OutColor : SV_Target0
)
{
    uint Width;
    uint Height;
    uint NumberOfLevels;

    SourceTexture.GetDimensions(0, Width, Height, NumberOfLevels);
    float2 coords;
    coords.x = SvPosition.x / Width;
    coords.y = SvPosition.y / Height;
    float4 src = SourceTexture.SampleLevel(SourceTextureSampler, coords, 0);

    //((pos * 1023.f) + 0.5f) / 1024.f centers positions in pixels centers;
    float pos = ((Grayscale(src) * 1023.f) + 0.5f) / 1024.f;
    //float pos = Grayscale(src);
    float4 result = AdjustCurveTexture.SampleLevel(AdjustCurveTextureSampler, float2(1.f - pos, 0.5f), 0);


    //Color Adjustments
    float3 hsv = LinearRGB_2_HSV(src.xyz);
    hsv.y = hsv.y * ColorSaturation;
    hsv.z = hsv.z * ColorValue;
    src.xyz = HSV_2_LinearRGB(hsv);

    OutColor.x = src.x;
    OutColor.y = src.y;
    OutColor.z = src.z;
    OutColor.w = result.x;

    //Grey
    /* OutColor.x = 0.f;//src.x;
    OutColor.y = 0.f;//src.y;
    OutColor.z = 0.f;//src.z;
    OutColor.w = result.x; */

    //OutColor.w = 1.0f - Grayscale(src);
    //OutColor.w = coords.x;

    //pos = ((coords.x * 1023.f) + 0.5f) / 1024.f;
    //OutColor.w = AdjustCurveTexture.Sample(AdjustCurveTextureSampler, float2(pos, 0.5f));
}
