#pragma once

#include <blend2d.h>
#include <Core/Core.h>
#include <Image/Block.h>

#include "OdysseyVectorObject.h"
#include "OdysseyVectorPoint.h"
#include "OdysseyVectorSection.h"
#include "OdysseyVectorSegmentCubic.h"
#include "OdysseyVectorPath.h"
#include "OdysseyVectorBucket.h"

class ODYSSEYVECTOR_API FOdysseyVectorCycle
{
    private:
        void BuildSegmentCubic( FOdysseyVectorSegmentCubic& iSegment
                              , double iFromT
                              , double iToT );

        /**
         * @brief build the cycle from vertices/sections passed as parameter. Sections can belong to different paths.
         * @param iVertexArray
         * @param iSectionArray drawing flags.
         */
        void Build( std::vector<FOdysseyVectorVertex*>& iVertexArray
                  , std::vector<FOdysseyVectorSection*>& iSectionArray );


    public:
        /*static FOdysseyVectorCycle* Exists( uint64 iID
                                          , std::vector<FOdysseyVectorVertex*>& iVertexArray
                                          , std::vector<FOdysseyVectorSection*>& iSectionArray );*/

        /**
         * @brief Generate an ID by XORing the pointer value of each section composing the cycle.
         * @return the generated ID.
         */
        static uint64 GenerateID( std::vector<FOdysseyVectorSection*>& iSectionArray );

        /**
         * @brief destructor.
         */
        ~FOdysseyVectorCycle();

        /**
         * @brief constructor.
         * @param iParent the parent object.
         * @param iID the cycle ID as generated by FOdysseyVectorCycle::GenerateID().
         * @param iVertexArray the vertex array.
         * @param iSectionArray the section array.
         */
         FOdysseyVectorCycle( UOdysseyVectorObject& iParent
                            , uint64 iID
                            , std::vector<FOdysseyVectorVertex*>& iVertexArray
                            , std::vector<FOdysseyVectorSection*>& iSectionArray );

        /**
         * @brief draw the cycle (in parent coordinates system).
         * @param iRoi region-of-interest.
         * @param iFlags drawing flags.
         */
        void Draw( ::ULIS::FRectD& iRoi, uint64 iFlags );

        /**
         * @brief collision test with coordinates passed as parameters.
         * @param iX local coordinate on X-Axis.
         * @param iY local coordinate on Y-Axis.
         */
        bool HitTest( double iLocalX, double iLocalY );

        /**
         * @brief Add a child cycle. A child cycle allows a parent cycle to have holes.
         * @param iChild the child cycle.
         */
        void AppendChild( FOdysseyVectorCycle *iChild );

        /**
         * @brief Remove a child cycle. A child cycle allows a parent cycle to have holes.
         * @param iChild the child cycle.
         */
        void RemoveChild( FOdysseyVectorCycle *iChild );

        /**
         * @brief Get this cycle's parent cycle.
         * @return this cycle's parent cycle.
         */
        FOdysseyVectorCycle* GetParentCycle();

        /**
         * @brief Get the attached bucket, if any.
         * @return the attached bucket or nullptr if none.
         */
        FOdysseyVectorBucket* GetBucket();

        /**
         * @brief Attach a bucket. Can be nullptr.
         * @param iBucket the bucket to attach.
         */
        void SetBucket( FOdysseyVectorBucket* iBucket );

        /**
         * @brief Test whether or not this cycle fits entirely within the cycle passed as parameter.
         * @param iParentCandidate the candidate parent cycle.
         */
        bool FitsIn( FOdysseyVectorCycle* iParentCandidate );

        /**
         * @brief Block all sections belonging to this cycle.
         */
        void Block();

        /**
         * @brief Unblock all sections belonging to this cycle.
         */
        void UnBlock();

        /**
         * @brief Get this cycle's ID.
         * @return this cycle ID
         */
        uint64 GetID();

    protected :
        BLPath mPath;
        UOdysseyVectorObject& mParent;
        uint64 mID;
        FOdysseyVectorBucket* mBucket;
        std::vector<FOdysseyVectorVertex*> mVertexArray;
        std::vector<FOdysseyVectorSection*> mSectionArray;
        uint32 mFlags;
        ::ULIS::FVec2D mMin;
        ::ULIS::FVec2D mMax;
        std::list<FOdysseyVectorCycle*> mChildrenList;
        FOdysseyVectorCycle* mParentCycle;
};
