#pragma once

#include <blend2d.h>
#include <Core/Core.h>
#include <Image/Block.h>

#include "OdysseyVectorObject.h"
#include "OdysseyVectorPoint.h"
#include "OdysseyVectorSection.h"
#include "OdysseyVectorSegmentCubic.h"
#include "OdysseyVectorPath.h"
#include "OdysseyVectorBucket.h"

class FOdysseyVectorSegmentCubic;

class ODYSSEYVECTOR_API FOdysseyVectorCycle
{
    private:
        /**
         * @brief build the cycle from vertices/sections passed as parameter. Sections can belong to different paths.
         * @param iVertexArray
         * @param iSectionArray drawing flags.
         */
        void Build( std::vector<FOdysseyVectorVertex*>& iVertexArray
                  , std::vector<FOdysseyVectorSection*>& iSectionArray );

    public:
        void ToBucketArray( std::vector<FOdysseyVectorCycle*>& iCyleArray
                          , std::vector<FOdysseyVectorBucket*>& oBucketArray );

        /**
         * @brief destructor.
         */
        ~FOdysseyVectorCycle();

        /**
         * @brief constructor.
         * @param iParent the parent object.
         * @param iID the cycle ID as generated by FOdysseyVectorCycle::GenerateID().
         * @param iVertexArray the vertex array.
         * @param iSectionArray the section array.
         */
         FOdysseyVectorCycle( FOdysseyVectorObject* iOwner
                            , std::vector<FOdysseyVectorVertex*>& iVertexArray
                            , std::vector<FOdysseyVectorSection*>& iSectionArray );

        /**
         * @brief draw the cycle (in parent coordinates system).
         * @param iFlags drawing flags.
         */
        void Draw( BLContext* iBLContext, double iOpacity, uint64 iFlags, bool iMonochrome, FColor iMonochromeColor );

        /**
         * @brief collision test with coordinates passed as parameters.
         * @param iX local coordinate on X-Axis.
         * @param iY local coordinate on Y-Axis.
         */
        bool HitTest( double iLocalX, double iLocalY );

        /**
         * @brief Set this cycle's parent cycle (the cycle that this one fits in).
         * @param iParent a pointer to this cycle's parent cycle.
         */
        void SetParentCycle( FOdysseyVectorCycle *iParent );

        /**
         * @brief Get this cycle's parent cycle.
         * @return this cycle's parent cycle.
         */
        FOdysseyVectorCycle* GetParentCycle();

        /**
         * @brief Get the attached bucket, if any.
         * @return the attached bucket or nullptr if none.
         */
        FOdysseyVectorBucket* GetBucket();

        /**
         * @brief Attach a bucket. Can be nullptr.
         * @param iBucket the bucket to attach.
         */
        void SetBucket( FOdysseyVectorBucket* iBucket );

        /**
         * @brief Test whether or not this cycle fits entirely within the cycle passed as parameter.
         * @param iParentCandidate the candidate parent cycle.
         */
        bool FitsIn( FOdysseyVectorCycle* iParentCandidate );

        /**
         * @brief Sets a bucket that should color this cycle without being its official bucket.
         * @param iPropagatedBucket the propagated bucket
         */
        void SetPropagatedBucket( FOdysseyVectorBucket* iPropagatedBucket );

        /**
         * @brief Gets the bucket that should color this cycle without being its official bucket.
         * @return a pointer to the propagated bucket
         */
        FOdysseyVectorBucket* GetPropagatedBucket();

        /**
         * @brief Gets a propagated bucket from any neighbour cycle
         * @return true if it got any, false otherwise
         */
        bool PropagateBucket();

        /**
         * @brief Merge this cycle's contour path with the contour path of the cycle passed as parameter
         * thus creating a combined path.
         * @param iMergeCycle the cycle that will be merged.
         */
        void Merge( FOdysseyVectorCycle* iMergeCycle );

        /**
         * @brief Stroke the path using BLend2D API. The context (path width, color) can be set before calling this method.
         * @param iWorld true if it should be drawn in world coordinates, false otherwise
         */
        void StrokePath( BLContext* iBLContext, bool iWorld );

        ::ULIS::FRectD GetBBox();

        FOdysseyVectorObject* GetOwner();

    private :
        bool PropagateBucket( std::vector<FOdysseyVectorSection*> iSectionArray );

    protected :
        BLPath mContourPath;
        BLPath mCombinedPath;
        FOdysseyVectorObject* mOwner;
        FOdysseyVectorBucket* mBucket;
        FOdysseyVectorBucket* mPropagatedBucket;
        std::vector<FOdysseyVectorVertex*> mVertexArray;
        std::vector<FOdysseyVectorSection*> mSectionArray;
        std::vector<FOdysseyVectorSection*> mInnerSectionArray;
        std::list<FOdysseyVectorCycle*> mChildrenList;
        FOdysseyVectorCycle* mParentCycle;
        bool mPropagated;
};
