// IDDN FR.001.250001.005.S.P.2019.000.00000
// ILIAD is subject to copyright laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2022

#pragma once

#include "LayerStack/OdysseyTextureLayer.h"
#include "Image/OdysseyBlendingMode.h"

#include "OdysseyTextureLayerFolder.generated.h"

UCLASS(BlueprintType)
class ODYSSEYTEXTURE_API UOdysseyTextureLayerFolder
    : public UOdysseyTextureLayer
{
    GENERATED_BODY()

public:
    /**
     * @brief Delegate called when something changed the result of RenderImage()
     * 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnBlendModeChanged, UOdysseyTextureLayerFolder*)

    /**
     * @brief Delegate called when something changed the result of RenderImage()
     * 
     */
    DECLARE_MULTICAST_DELEGATE_OneParam(FOnOpacityChanged, UOdysseyTextureLayerFolder*)

public:
    static FOnBlendModeChanged& OnBlendModeChanged();
    static FOnOpacityChanged& OnOpacityChanged();

public:
    UOdysseyTextureLayerFolder();

public:
    //IOdysseyTextureLayerImageRenderer implementation
    
    /**
     * @brief Renders an image in the given Block
     * Takes into account the size / format of the given block
     * 
     */
    virtual TArray<::ULIS::FEvent> RenderImage(TSharedPtr<::ULIS::FBlock, ESPMode::ThreadSafe> ioBlock, const ::ULIS::FRectI& iRect, const ::ULIS::FVec2I& iPos, const TArray<::ULIS::FEvent>& iWaitList);

    /**
     * @brief Copies an image in the given Block
     * Takes into account the size / format of the given block
     */
    virtual TArray<::ULIS::FEvent> CopyImage(TSharedPtr<::ULIS::FBlock, ESPMode::ThreadSafe> ioBlock, const ::ULIS::FRectI& iRect, const ::ULIS::FVec2I& iPos, const TArray<::ULIS::FEvent>& iWaitList);

public:
    // UOdysseyLayer Overrides

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const override;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> iLayerTypes) const override;

private:
    //Property changed methods
    void OpacityChanged();
    void BlendModeChanged();

    virtual void PropertyChanged(const FName& iPropertyName) override;

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Texture | LayerStack")
	EOdysseyBlendingMode BlendMode = EOdysseyBlendingMode::kNormal;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Texture | LayerStack")
    float Opacity = 1.0f;
};