; https://udn.unrealengine.com/s/question/0D54z00006tMlfbCAC/plugin-cconfig-how-to-use-config-ini-file-for-a-custom-plugin-
; This config file is used when the plugin is inside Engine folder (for release)
; This file will be copied (during pre-build-steps) in DefaultEpos.ini to be able to use this config when the plugin is inside a project (for development)

[/Script/EposTracksEditor.EposTracksEditorSettings]
; See BaseEngine.ini at [/Script/CinematicCamera.CineCameraComponent]
CameraSettings=(Filmback=(SensorWidth=23.76,SensorHeight=13.365),LensSettings=(MinFocalLength=4,MaxFocalLength=1000,MinFStop=1.2,MaxFStop=22,DiaphragmBladeCount=7),FocusSettings=(ManualFocusDistance=200.000000),CurrentAperture=16,CurrentFocalLength=35)
TextureSettings=(Height=1080)
DefaultSectionDuration=3.0
BoardTrackSettings=(BoardSectionColor=(R=.94,G=.39,B=.6,A=.25),ShotSectionColor=(R=.6,G=.39,B=.94,A=.25))

[/Script/EposSequenceEditor.EposSequenceEditorSettings]
; See BaseEngine.ini at [/Script/CinematicCamera.CineCameraComponent]
BoardSettings=(DefaultTickFrameRate=(Numerator=24000,Denominator=1),DefaultDisplayFrameRate=(Numerator=24,Denominator=1))
ShotSettings=(DefaultTickFrameRate=(Numerator=24000,Denominator=1),DefaultDisplayFrameRate=(Numerator=24,Denominator=1))

[/Script/EposTracks.EposTracksSettings]
BoardTrackSettings=(ArrangeSections=OnOneRow)

;---

[EposSequencerEditor SequencerSettings]
bKeyInterpPropertiesOnly=true
bShowRangeSlider=true
bKeepPlayRangeInSectionBounds=true
ZeroPadFrames=4
bInfiniteKeyAreas=true
bAutoSetTrackDefaults=true
FrameNumberDisplayFormat=Frames
KeyGroupMode=KeyAll
AutoChangeMode=AutoKey

;---
;---
;---

[OdysseyTelemetry.Config]
SendTelemetry=True

[OdysseyTelemetry.Provider]
; Enabled=False
; UsageType=EditorAndClientAndServer
UsageType=Editor
APIKeyOdyssey=OdysseyAnalytics
APIServerOdyssey="https://ingest.telemetry.praxinos.coop/"
APIEndpointOdyssey="v1/events"

; This is used when building a not "Development Editor" mode
; Then, all events are always send but can be filtered on the web side
; (and certainly ignored in this case)
[OdysseyTelemetry.Provider-Debug]
UsageType=Editor
APIKeyOdyssey=OdysseyAnalytics.Debug
; HTTP = NOT SECURE !!!
APIServerOdyssey="http://127.0.0.1:8080/"
APIEndpointOdyssey="v1/events"

;---
;---
;---

[CoreRedirects]
+PackageRedirects=(OldName="/Iliad/...",NewName="/Odyssey/", MatchWildcard=true)
+PackageRedirects=(OldName="/Epos/...",NewName="/Odyssey/", MatchWildcard=true)

;LayerStack
+ClassRedirects=(OldName="OdysseyLayerStack", NewName="/Script/OdysseyLayerStack.OdysseyLayerStack")
+ClassRedirects=(OldName="OdysseyLayerRoot", NewName="/Script/OdysseyLayerStack.OdysseyLayerRoot")
+ClassRedirects=(OldName="OdysseyLayer", NewName="/Script/OdysseyLayerStack.OdysseyLayer")

; Animation
+ClassRedirects=(OldName="OdysseyAnimationLayerRoot", NewName="/Script/OdysseyLayerStack.OdysseyLayerRoot")
+ClassRedirects=(OldName="/Script/OdysseyLayerStackEditor.OdysseyAnimationLayer...", NewName="/Script/OdysseyAnimation.OdysseyAnimationLayer", MatchWildcard=true)
+ClassRedirects=(OldName="/Script/OdysseyLayerStackEditor.OdysseyAnimationCell...", NewName="/Script/OdysseyAnimation.OdysseyAnimationCell", MatchWildcard=true)

; Texture

; We don't redirect OdysseyTextureAssetUserData because it contained the old non UObject layerstack, which is now impossible to load anymore
; Activating this would create crashes on some assets
; Instead we assume those assets generates warnings about OdysseyTextureAssetUserData not existing
; If you want to get rid of those warnings, just resave the asset.
; Opening this kind of asset will just recreate a default layerstack.
; +ClassRedirects=(OldName="OdysseyTextureAssetUserData", NewName="/Script/OdysseyTexture.OdysseyTextureLayerStackUserData")

+ClassRedirects=(OldName="OdysseyTextureLayerStackUserData", NewName="/Script/OdysseyTexture.OdysseyTextureLayerStackUserData")
+ClassRedirects=(OldName="OdysseyTextureLayerStack", NewName="/Script/OdysseyTexture.OdysseyTextureLayerStack")
+ClassRedirects=(OldName="OdysseyTextureLayerRoot", NewName="/Script/OdysseyLayerStack.OdysseyLayerRoot")
+ClassRedirects=(OldName="OdysseyTextureLayerFolder", NewName="/Script/OdysseyTexture.OdysseyTextureLayerFolder")
+ClassRedirects=(OldName="OdysseyTextureLayerImageRaster", NewName="/Script/OdysseyTexture.OdysseyTextureLayerImageRaster")
+ClassRedirects=(OldName="OdysseyTextureLayerImageVector", NewName="/Script/OdysseyTexture.OdysseyTextureLayerImageVector")


; +PackageRedirects=(OldName="/Script/OdysseyShapes/...",NewName="/Odyssey/OdysseyPainterEditor/", MatchWildcard=true)
+ClassRedirects=(OldName="/Script/OdysseyShapes.OdysseyFreehandShapeOverrides",NewName="/Script/OdysseyPainterEditor.OdysseyFreehandShapeOverrides")
+EnumRedirects=(OldName="/Script/OdysseyCore.EOdysseyAlphaMode",NewName="/Script/OdysseyRendering.EOdysseyAlphaMode")
+EnumRedirects=(OldName="/Script/OdysseyCore.EOdysseyBlendingMode",NewName="/Script/OdysseyRendering.EOdysseyBlendingMode")
+EnumRedirects=(OldName="/Script/OdysseyLayerStackEditor.EOdysseyAnimationLayerImagePostBehaviour",NewName="/Script/OdysseyLayerStack.EOdysseyLayerImagePostBehaviour")
+EnumRedirects=(OldName="/Script/OdysseyLayerStackEditor.EOdysseyLayerCellImageStaggerBehaviour",NewName="/Script/OdysseyLayerStack.EOdysseyLayerCellImageStaggerBehaviour")

; Storyboard cleaning: move all assets inside directories
+PackageRedirects=(OldName="/Odyssey/S_1_Unit_Plane",NewName="/Odyssey/Meshes/S_1_Unit_Plane")
+PackageRedirects=(OldName="/Odyssey/T_PDFBox_FilledBorder",NewName="/Odyssey/PDF/T_PDFBox_FilledBorder")
; Materials
+PackageRedirects=(OldName="/Odyssey/M_Plane",NewName="/Odyssey/Materials/M_Plane")
+PackageRedirects=(OldName="/Odyssey/T_Transparent",NewName="/Odyssey/Materials/T_Transparent")
+PackageRedirects=(OldName="/Odyssey/MF_BlendNormal",NewName="/Odyssey/Materials/MF_BlendNormal")
+PackageRedirects=(OldName="/Odyssey/MF_DrawGrid",NewName="/Odyssey/Materials/MF_DrawGrid")
+PackageRedirects=(OldName="/Odyssey/MF_DrawLine2D",NewName="/Odyssey/Materials/MF_DrawLine2D")
+PackageRedirects=(OldName="/Odyssey/MF_SwitchToOneColor",NewName="/Odyssey/Materials/MF_SwitchToOneColor")
; Render
+PackageRedirects=(OldName="/Odyssey/MPMC_Storyboard_Sequence",NewName="/Odyssey/Render/MPMC_Storyboard_Sequence")
+PackageRedirects=(OldName="/Odyssey/MPMC_Storyboard_Video_FFmpeg",NewName="/Odyssey/Render/MPMC_Storyboard_Video_FFmpeg")
+PackageRedirects=(OldName="/Odyssey/WBP_StoryboardBurnIn",NewName="/Odyssey/Render/WBP_StoryboardBurnIn")
+PackageRedirects=(OldName="/Odyssey/WBP_StoryboardNoteWidgetRow",NewName="/Odyssey/Render/WBP_StoryboardNoteWidgetRow")
