[/Script/UnrealEd.ContentBrowserSettings]
; Whether to display the engine folders in the assets view of the content browser. Note that this implies 'Display Folders'.
DisplayEngineFolder=True
; Whether to display the game project plugins in the Content Browser
DisplayPluginFolder=True
