[CoreRedirects]
+EnumRedirects=(OldName="/Script/OdysseyBrush.EOdysseyBlendingMode",NewName="/Script/OdysseyCore.EOdysseyBlendingMode")
+EnumRedirects=(OldName="/Script/OdysseyBrush.EOdysseyAlphaMode",NewName="/Script/OdysseyCore.EOdysseyAlphaMode")

#+PropertyRedirects=(OldName="OdysseyLayer.IsExpanded",NewName="OdysseyLayer.DisplayChildren")
#+PropertyRedirects=(OldName="OdysseyLayer.IsCollapsed",NewName="OdysseyLayer.DisplayOptions")