// IDDN.FR.001.250001.005.S.P.2019.000.00000
// ILIAD is subject to copyright laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2022

#pragma once

#include <blend2d.h>
#include <Core/Core.h>
#include <list>
#include <Image/Block.h>

class FOdysseyVectorObject;
class FOdysseyVectorSection;
class FOdysseyVectorBucket;
class FOdysseyVectorVertex;

class ODYSSEYVECTOR_API FOdysseyVectorCycle
{
    public:
        friend class FOdysseyVectorGroupPaint;

        /**
         * @brief build the cycle from vertices/sections passed as parameter. Sections can belong to different paths.
         * @param iVertexArray
         * @param iSectionArray drawing flags.
         */
        void Build( /*std::vector<FOdysseyVectorVertex*>& iVertexArray
                  , std::vector<FOdysseyVectorSection*>& iSectionArray*/ );


        void ToBucketArray( std::vector<FOdysseyVectorCycle*>& iCyleArray
                          , std::vector<FOdysseyVectorBucket*>& oBucketArray );

        /**
         * @brief destructor.
         */
        ~FOdysseyVectorCycle();

        /**
         * @brief constructor.
         * @param iParent the parent object.
         * @param iID the cycle ID as generated by FOdysseyVectorCycle::GenerateID().
         * @param iVertexIndexArray the vertex array as indexes (0 or 1).
         * @param iSectionArray the section array.
         */
         FOdysseyVectorCycle( FOdysseyVectorObject* iOwner
                            , const std::vector<uint32>& iVertexIndexArray
                            , const std::vector<FOdysseyVectorSection*>& iSectionArray );

        /**
         * @brief draw the cycle (in parent coordinates system).
         * @param iFlags drawing flags.
         */
        void Draw( BLContext* iBLContext
                 , double iOpacity
                 , uint64 iFlags
                 , bool iMonochrome
                 , FColor iMonochromeColor );

        /**
         * @brief Test whether or not this cycle fits entirely within the cycle passed as parameter.
         * @param iParentCandidate the candidate parent cycle.
         */
        bool FitsIn( FOdysseyVectorCycle* iParentCandidate );

        /**
         * @brief Gets this cycle's bounding box
         * @return the bounding box as a rectangle
         */
        ::ULIS::FRectD GetBBox( bool iWorld );

        /**
         * @brief Get the attached bucket, if any.
         * @return the attached bucket or nullptr if none.
         */
        FOdysseyVectorBucket* GetBucket();

        /**
         * @brief Get the pointer to this cycle's owner object
         * @return a pointer to this cycle's owner object
         */
        FOdysseyVectorObject* GetOwner();

        /**
         * @brief Get this cycle's parent cycle.
         * @return this cycle's parent cycle.
         */
        FOdysseyVectorCycle* GetParentCycle();

        /**
         * @brief Gets the bucket that should color this cycle without being its official bucket.
         * @return a pointer to the propagated bucket
         */
        FOdysseyVectorBucket* GetPropagatedBucket();

        /**
         * @brief collision test with coordinates passed as parameters.
         * @param iX local coordinate on X-Axis.
         * @param iY local coordinate on Y-Axis.
         */
        bool HitTest( double iLocalX, double iLocalY );

        /**
         * @brief Merge this cycle's contour path with the contour path of the cycle passed as parameter
         * thus creating a combined path.
         * @param iMergeCycle the cycle that will be merged.
         */
        void Merge( FOdysseyVectorCycle* iMergeCycle );

        /**
         * @brief Gets a propagated bucket from any neighbour cycle
         * @return true if it got any, false otherwise
         */
        void PropagateBucket( std::vector<FOdysseyVectorCycle*>& oNextCycleArray );

        /**
         * @brief Attach a bucket. Can be nullptr.
         * @param iBucket the bucket to attach.
         */
        void SetBucket( FOdysseyVectorBucket* iBucket );

        /**
         * @brief Set this cycle's parent cycle (the cycle that this one fits in).
         * @param iParent a pointer to this cycle's parent cycle.
         */
        void SetParentCycle( FOdysseyVectorCycle *iParent );

        /**
         * @brief Sets a bucket that should color this cycle without being its official bucket.
         * @param iPropagatedBucket the propagated bucket
         */
        void SetPropagatedBucket( FOdysseyVectorBucket* iPropagatedBucket );

        /**
         * @brief Stroke the path using BLend2D API. The context (path width, color) can be set before calling this method.
         * @param iWorld true if it should be drawn in world coordinates, false otherwise
         */
        void StrokePath( BLContext* iBLContext, bool iWorld );

    private :
        void PropagateBucket( std::vector<FOdysseyVectorSection*> iSectionArray
                            , std::vector<FOdysseyVectorCycle*>& oNextCycleArray );

        bool HasVertex( FOdysseyVectorVertex* iVertex );

    protected :
        BLPath mContourPath;
        BLPath mCombinedPath;
        FOdysseyVectorObject* mOwner;
        FOdysseyVectorBucket* mBucket;
        FOdysseyVectorBucket* mPropagatedBucket;
        std::vector<uint32> mContourVertexIndexArray;
        std::vector<FOdysseyVectorSection*> mContourSectionArray;
        std::vector<FOdysseyVectorSection*> mInnerSectionArray;
        std::list<FOdysseyVectorCycle*> mChildrenList;
        FOdysseyVectorCycle* mParentCycle;
        ::ULIS::FRectD mBBox;
        bool mPropagated;
};
