// IDDN.FR.001.060015.014.S.X.2019.000.00000
// ODYSSEY is subject to copyright © laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2019

#pragma once

#include "OdysseyAnimationLayer.h"
#include "OdysseyAnimationLayerFolder.generated.h"

UCLASS(BlueprintType)
class ODYSSEYANIMATION_API UOdysseyAnimationLayerFolder
    : public UOdysseyAnimationLayer
{
    GENERATED_BODY()

public:
    UOdysseyAnimationLayerFolder();

#if WITH_EDITOR
public:
    // UOdysseyLayer Overrides

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const override;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> iLayerTypes) const override;
#endif
};
