// IDDN FR.001.250001.005.S.P.2019.000.00000
// ILIAD is subject to copyright laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2022

#pragma once

#include "LayerStack/Layers/OdysseyAnimationLayer.h"
#include "OdysseyAnimationLayerFolder.generated.h"

UCLASS(BlueprintType)
class ODYSSEYANIMATION_API UOdysseyAnimationLayerFolder
    : public UOdysseyAnimationLayer
{
    GENERATED_BODY()

public:
    UOdysseyAnimationLayerFolder();

public:
#ifdef WITH_EDITOR
	virtual FOptionalSize GetRowHeight(FName iSubRowName) const override;
#endif

public:
    // UOdysseyLayer Overrides

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const override;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     * 
     * @return TSet<UClass*> 
     */
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> iLayerTypes) const override;
};