// IDDN.FR.001.060015.013.S.X.2019.000.00000
// ODYSSEY is subject to copyright © laws and is the legal and intellectual property of Praxinos,Inc - Year of publishing 2019

#pragma once

#include "OdysseyTextureLayer.h"
#include "OdysseyTextureLayerFolder.generated.h"

UCLASS(BlueprintType)
class ODYSSEYTEXTURE_API UOdysseyTextureLayerFolder
    : public UOdysseyTextureLayer
{
    GENERATED_BODY()

public:
    UOdysseyTextureLayerFolder();

public:
    // UOdysseyLayer Overrides

    /**
     * @brief Returns the layer types generated by this layer if a merge is called on it right now
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    virtual TSet<UClass*> GetMergeDefaultLayerTypes() const override;

    /**
     * @brief Returns the layer types generated by this layer if it is merged as part of one of the given layer types
     * Can change depending on the layer content or configuration (ex: layer folder children layer types)
     *
     * @return TSet<UClass*>
     */
    virtual TSet<UClass*> GetMergeLayerTypesFromTypes(TSet<UClass*> iLayerTypes) const override;
};
